apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: eks
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://aws.github.io/eks-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  releaseName: aws-load-balancer-controller
  targetNamespace: kube-system
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: flux-system
  interval: 2m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    clusterName: us2-eks-cluster
    vpcId: vpc-0de6ec4f3f0de4973
    region: us-east-2
    serviceAccount:
      name: aws-load-balancer-controller
      create: false
